# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
text = s.split()
print(text)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
text= "the diameter of the earth is {size:5} kilometers"
print(text.format(size=12742))

the diameter of the earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print('hello')

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
a=['0','0','0','0','0','0','0','0','0','0']

In [ ]:
a=['5','5','5','5','5','5','5','5','5','5']

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array) 

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

NameError: ignored

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [24]:
import pandas as pd 
data=[10,20,30]
df=pd.DataFrame(data,columns=[''])
df

0  10
1  20
2  30

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [30]:
import pandas as pd
data = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(data,columns=['Num1','Name', 'Num2'])
print(df)
 

   Num1 Name  Num2
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24
